title: DevSecOps Days Boston
email: organizers@devsecopsdaysboston.org
description: >- # this means to ignore newlines until "baseurl:"
  An onboing, online event for DevOps and Security practitioners
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devsecopsdaysboston.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: devsecopsdaysboston
github_username:  DevSecOpsDaysBoston
show_github: false
google_analytics_tag: G-PD571HKSPK
produrl: "https://devsecopsdaysboston.org"
event_short_title: DevSecOps Days Boston

current_event:
  dates: "June 26th"

registration:
  is_open: true
  direct_link: "https://dashboard.tito.io/devsecops-days-boston/2021"
  relative_path: "/signup"

cfp:
  is_open: true
  open_date: "June 4th"
  close_date: "June 28th"
  direct_link: "https://www.papercall.io/devsecops-days-boston-2021"


# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

include:
  - _pages

header_pages:
  - title: "-about"
    url: /about
  - title: "-signup"
    url: /signup
  - title: "-cfp"
    url: https://www.papercall.io/devsecops-days-boston-2021
  # - title: "-agenda"
  #   url: /agenda
  - title: "-code-of-conduct"
    url: /code-of-conduct
  - title: "-sponsor"
    url: "/sponsor"
  - title: "-contact"
    url: "/contact"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
